# Numpy Part 1: Numpy Fundamentals and Essentials

In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv("../data/iris.csv")
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [52]:
iris_numerical = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)']].values

In [53]:
iris_numerical

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Numpy Array

- Membuat numpy array **(Hanya bisa berisikan sebuah angka)**
- Membuat array dengan semua nilai 0
- Membuat array dengan semua nilainya 1
- Membuat array dengan range
- Membuat array dengan nilai random

### Membuat sebuah array

In [54]:
python_list = [1, 2, 3]
array = np.array(python_list)
print(list)
print(array)

<class 'list'>
[1 2 3]


In [55]:
array[1]

np.int64(2)

### Membuat array dengan semua nilai 0
`np.zeros()`

In [56]:
zeros_array = np.zeros([2, 3, 2])
zeros_array

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### Membuat array dengan semua nilai 1
`np.ones()`

In [57]:
ones_array = np.ones([3, 3])
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Membuat sebuah array dengan range
`np.arange()` -> (start, stop, step)

In [58]:
arange_array = np.arange(1, 11, 1)
arange_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Membuat array dengan nilai random
- `np.random.rand()` -> Nilai max tidak lebih dari 1 -> Random float
- `np.random.randint()` -> Masukkan nilai bawah + atas + size ->Random int

In [59]:
float_random = np.random.rand(3, 5)
float_random

array([[0.52610999, 0.65076859, 0.96073141, 0.09507219, 0.09291028],
       [0.21231079, 0.32541917, 0.34272356, 0.72199106, 0.7589634 ],
       [0.30073157, 0.26465757, 0.36205472, 0.21419627, 0.87523734]])

In [60]:
int_random = np.random.randint(1, 10, [2, 2])
int_random

array([[4, 3],
       [9, 3]], dtype=int32)

## Reshaping Array

In [61]:
old_array = np.arange(1, 11)
old_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
old_array_reshape = old_array.reshape(2, 5)
old_array_reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Indexing and Slicing
- Formatnya: ***[row, columns] -> [start:end:step, start,end,step]***

In [63]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [64]:
iris_numerical[0, 0]

np.float64(5.1)

In [65]:
iris_numerical[0:4, 0:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1]])

In [66]:
df_lebih_dari5 = iris_numerical[iris_numerical[:, 0] > 5.0]
df_lebih_dari5

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2

# Numpy Part 2: Broadcasting

In [67]:
data = np.random.randint(1, 100,[3, 3])
data

array([[12, 11,  2],
       [82, 48, 55],
       [47, 66, 21]], dtype=int32)

In [69]:
# np.sqrt()
data_sqrt = np.sqrt(data)
data_sqrt

array([[3.46410162, 3.31662479, 1.41421356],
       [9.05538514, 6.92820323, 7.41619849],
       [6.8556546 , 8.1240384 , 4.58257569]])

In [70]:
#np.log()
data_log = np.log(data)
data_log

array([[2.48490665, 2.39789527, 0.69314718],
       [4.40671925, 3.87120101, 4.00733319],
       [3.8501476 , 4.18965474, 3.04452244]])

In [71]:
data_log2 = np.log2(data)
data_log2

array([[3.5849625 , 3.45943162, 1.        ],
       [6.357552  , 5.5849625 , 5.78135971],
       [5.55458885, 6.04439412, 4.39231742]])

## Dot Product & Matrix Multiplication
- Dot Product adalah `Vektor` x `Vektor` = `Scalar`
- Matrix Multiplication adalah `Matrix` x `Matrix` = `Matrix`

In [73]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

hasil = np.dot(v1, v2)
hasil

np.int64(32)

In [77]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6]])
m2 = np.array([[7, 8, 9], 
               [10, 11, 12],
               [13, 14, 15]])

hasil = np.dot(m1, m2)
hasil

array([[ 66,  72,  78],
       [156, 171, 186]])

## Broadcasting
Lebih menyesuaikan data dimensi kecil ke yang besar

In [78]:
# Vektor dengan Scalar
v = np.array([1, 2, 3])
s = 10

hasil = np.dot(v, s)
hasil

array([10, 20, 30])

In [79]:
# Matrix dengan Vektor
m = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])

hasil = m + v
hasil

array([[11, 22, 33],
       [14, 25, 36]])

In [82]:
# np.concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

hasil = np.concatenate((arr1, arr2), axis=0)
hasil

array([1, 2, 3, 4, 5, 6])